---
- Beauty
- Biker
- Bird Keeper
- Blackbelt
- Boss
- Bug Catcher
- Burglar
- Champion
- Channeler
- Cooltrainer
- Cue Ball
- Elite Four
- Engineer
- Fisherman
- Gambler
- Gentleman
- Hiker
- Jr. Trainer
- Juggler
- Lass
- Leader
- PokéManiac
- Psychic
- Rival
- Rocker
- Rocket
- Sailor
- Scientist
- Super Nerd
- Swimmer
- Tamer
- Youngster